apiVersion: v1
kind: Service
metadata:
  name: app-server-service
spec:
  type: NodePort
  selector:
    app: chibsappV1
  ports:
    - name: http
      protocol: TCP
      nodePort: 8081
      port: 80
      targetPort: 81