apiVersion: v1
kind: Service
metadata:
  name: app-server-service
spec:
  type: NodePort
  selector:
    app: chibsapp
  ports:
    - name: http
      protocol: TCP
      nodePort: 32123
      port: 8080
      targetPort: 81